<a href="https://colab.research.google.com/github/Naushad13b/Machine-Learning/blob/main/02)DataCleaning1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data=pd.read_csv("new111.csv")

In [ ]:
data.head(50)

,From Date,To Date,PM2.5,PM10,NO2,SO2,CO,Ozone,Temp,RH,WS,WD,SR
0,17-10-2017 00:00,18-10-2017 00:00,142.91,583.89,100.53,172.35,1.42,50.59,30.74,25.48,1.40,253.25,-99.99
1,18-10-2017 00:00,19-10-2017 00:00,182.46,431.33,80.65,59.88,1.01,46.94,27.25,40.72,1.36,237.65,-99.99
2,19-10-2017 00:00,20-10-2017 00:00,268.01,400.41,74.95,37.55,1.07,70.18,28.01,44.63,1.11,176.48,-99.99
3,20-10-2017 00:00,21-10-2017 00:00,254.79,280.44,59.43,21.04,0.96,57.11,28.56,40.79,1.14,189.95,-99.99
4,21-10-2017 00:00,22-10-2017 00:00,288.70,362.84,90.75,60.34,1.05,57.99,27.50,40.27,1.25,222.88,-99.99
5,22-10-2017 00:00,23-10-2017 00:00,219.31,377.96,105.01,74.42,0.96,35.97,28.28,29.27,1.17,192.67,-57.40
6,23-10-2017 00:00,24-10-2017 00:00,209.54,407.30,112.02,63.92,0.98,34.18,26.81,29.93,1.00,187.02,-28.72
7,24-10-2017 00:00,25-10-2017 00:00,235.58,412.40,121.52,97.21,1.13,38.29,26.81,31.32,1.28,215.25,-489.10
8,25-10-2017 00:00,26-10-2017 00:00,261.04,445.45,127.69,90.46,1.20,48.15,25.68,35.91,1.13,185.33,-489.44
9,26-10-2017 00:00,27-10-2017 00:00,202.26,354.93,104.12,62.65,1.05,70.93,25.95,38.46,1.17,139.07,-493.25
10,27-10-2017 00:00,28-10-2017 00:00,218.39,353.87,72.40,57.71,1.15,57.11,25.40,48.13,1.03,130.39,-165.34
11,28-10-2017 00:00,29-10-2017 00:00,190.31,304.91,86.60,112.46,0.97,72.89,26.32,40.39,1.18,132.11,518.45
12,29-10-2017 00:00,30-10-2017 00:00,215.68,336.41,86.38,102.08,1.12,67.75,25.37,48.26,1.07,116.19,518.84
13,30-10-2017 00:00,31-10-2017 00:00,257.46,420.01,107.04,74.69,1.26,52.22,24.64,51.29,1.18,175.82,523.08
14,31-10-2017 00:00,01-11-2017 00:00,255.52,417.48,97.32,65.61,1.25,68.88,24.67,49.81,1.10,151.03,541.63
15,01-11-2017 00:00,02-11-2017 00:00,272.51,392.59,71.97,81.19,1.31,70.57,25.19,51.01,1.06,113.39,537.89
16,02-11-2017 00:00,03-11-2017 00:00,229.88,360.75,104.41,68.53,1.26,55.53,24.95,53.20,1.33,177.87,534.97
17,03-11-2017 00:00,04-11-2017 00:00,234.76,361.01,86.17,81.79,1.16,56.38,24.64,59.51,1.07,115.68,541.99
18,04-11-2017 00:00,05-11-2017 00:00,218.18,311.55,71.76,41.26,1.16,45.28,23.97,67.88,1.05,124.04,545.92
19,05-11-2017 00:00,06-11-2017 00:00,242.45,376.56,99.57,33.95,1.02,37.26,23.82,58.66,1.05,142.99,540.08
20,06-11-2017 00:00,07-11-2017 00:00,251.75,409.27,133.13,74.95,1.08,35.33,23.52,50.34,1.18,195.96,542.22
21,07-11-2017 00:00,08-11-2017 00:00,356.80,534.85,119.21,69.32,1.41,43.97,24.59,40.99,1.28,190.38,541.78
22,08-11-2017 00:00,09-11-2017 00:00,444.56,605.55,126.97,79.55,1.89,46.88,22.89,45.63,1.21,200.77,553.08
23,09-11-2017 00:00,10-11-2017 00:00,389.04,525.29,119.45,73.77,1.44,45.50,23.17,36.66,1.18,168.61,561.48
24,10-11-2017 00:00,11-11-2017 00:00,415.92,586.90,110.57,49.48,2.06,34.09,22.34,49.53,1.14,170.37,559.53
25,11-11-2017 00:00,12-11-2017 00:00,311.59,493.91,78.19,55.97,1.80,44.16,22.50,45.28,1.09,169.54,562.97
26,12-11-2017 00:00,13-11-2017 00:00,401.46,547.14,59.74,21.79,1.93,47.52,22.07,52.41,1.09,169.81,560.90
27,13-11-2017 00:00,14-11-2017 00:00,401.23,551.70,65.21,20.90,1.99,45.29,21.72,54.53,1.01,138.14,553.69
28,14-11-2017 00:00,15-11-2017 00:00,179.51,289.27,44.27,13.40,1.16,42.71,20.29,51.80,1.18,143.00,525.95
29,15-11-2017 00:00,16-11-2017 00:00,164.24,322.01,36.09,39.87,1.27,51.73,20.73,56.91,0.86,131.26,541.84
30,16-11-2017 00:00,17-11-2017 00:00,175.30,351.11,56.84,135.24,1.35,32.93,20.27,60.99,1.24,179.40,555.00
31,17-11-2017 00:00,18-11-2017 00:00,153.84,295.07,51.30,113.44,1.09,23.77,19.97,65.45,1.55,258.82,565.36
32,18-11-2017 00:00,19-11-2017 00:00,132.08,263.92,50.75,78.79,1.15,30.32,20.02,65.35,1.67,295.17,557.39
33,19-11-2017 00:00,20-11-2017 00:00,164.56,313.57,60.37,105.93,0.90,35.78,19.44,46.64,1.98,306.78,567.49
34,20-11-2017 00:00,21-11-2017 00:00,132.59,290.26,66.68,97.19,0.94,32.16,17.47,45.91,1.38,250.12,554.29
35,21-11-2017 00:00,22-11-2017 00:00,124.64,297.27,76.95,66.20,1.11,29.00,17.76,40.84,1.19,230.71,561.79
36,22-11-2017 00:00,23-11-2017 00:00,112.74,282.06,63.94,64.16,0.92,30.56,17.76,37.36,1.27,232.04,563.70
37,23-11-2017 00:00,24-11-2017 00:00,415.06,284.84,74.28,73.88,0.97,31.49,17.57,36.15,1.15,231.19,905.44
38,24-11-2017 00:00,25-11-2017 00:00,118.16,295.40,80.24,57.99,1.09,29.75,17.60,37.91,0.91,196.36,759.10
39,25-11-2017 00:00,26-11-2017 00:00,162.90,439.73,89.28,70.99,1.43,26.55,16.90,39.35,1.06,203.72,560.53
40,26-11-2017 00:00,27-11-2017 00:00,177.74,419.75,82.78,79.96,1.08,24.33,18.07,40.51,0.95,199.26,548.01
41,27-11-2017 00:00,28-11-2017 00:00,120.60,340.36,101.74,62.62,0.73,27.18,17.29,39.97,1.30,216.78,532.86
42,28-11-2017 00:00,29-11-2017 00:00,141.19,382.95,79.41,52.62,1.33,20.50,19.45,39.66,1.03,179.75,561.48
43,29-11-2017 00:00,30-11-2017 00:00,241.68,637.58,115.88,38.34,0.42,9.91,17.65,44.52,1.09,150.07,568.65
44,30-11-2017 00:00,01-12-2017 00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,01-12-2017 00:00,02-12-2017 00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,02-12-2017 00:00,03-12-2017 00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,03-12-2017 00:00,04-12-2017 00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,04-12-2017 00:00,05-12-2017 00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,05-12-2017 00:00,06-12-2017 00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Mean - missed value first put None to NaN in dataset
import numpy as np
def change1(a):
  data[a] = data[a].replace(np.NaN, data[a].mean())

In [ ]:
#PM2.5	PM10	NO2	SO2	CO	Ozone	Temp	RH	WS	WD	SR
l=["PM2.5","PM10","NO2","SO2","CO","Ozone","RH","Temp","WS","WD","SR"]
for i in l:
  change1(i)

In [ ]:
# downloading csv file
cities = pd.DataFrame(data)
cities.to_csv('new222.csv')