<a href="https://colab.research.google.com/github/Naushad13b/Machine-Learning/blob/main/07)SotingDate_DownloadingData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from matplotlib.pylab import rcParams
rcParams['figure.figsize'] = 10,6

In [10]:
df = pd.read_csv(r"/content/Data.csv")

In [11]:
df.head(40)

,Station,Date,PM2.5,PM10,NO,NO2,SO2,CO,Ozone,Temp,RH,WS,WD,SR
0,1A,01-01-2021 00:00,228.53,349.22,19.35,43.16,26.73,1.53,33.3,14.69,49.07,0.42,132.16,69.6
1,1A,02-01-2021 00:00,222.37,313.72,13.3,36.83,31.7,1.73,28.9,16.76,46.97,0.47,117.2,43.07
2,1A,03-01-2021 00:00,128.14,177.7,15.94,29.33,24.19,1.29,17.46,17.26,70.07,0.5,107.32,26.13
3,1A,04-01-2021 00:00,68.44,104.81,26.27,40.26,21.8,1.13,14.43,19.5,72.69,0.72,143.68,70.3
4,1A,05-01-2021 00:00,62.51,104.2,22.32,40.63,20.09,0.98,16.6,20.87,73.33,0.67,85.33,70.81
5,1A,06-01-2021 00:00,122.99,185.76,56.59,68.72,21.6,1.25,8.85,19.49,88.84,1.15,244.78,24.45
6,1A,07-01-2021 00:00,119.15,214.43,38.48,57.54,37.88,1.03,14.09,18.75,75.21,1.23,258.4,89.83
7,1A,08-01-2021 00:00,121.51,224.98,33.89,41.65,55.02,1.12,9.3,15.49,86.91,0.88,175.98,41.26
8,1A,09-01-2021 00:00,156.75,273.34,40.73,55.38,56.47,1.18,8.75,17.32,81.27,1.56,305.57,51.18
9,1A,10-01-2021 00:00,119.35,227.9,37.11,52.61,59.9,0.79,8.27,13.46,80.45,1.76,306,13.24
10,1A,11-01-2021 00:00,90.12,218.45,54.14,78.02,39.01,0.97,15.7,13.67,75.12,1.44,293.99,73.27
11,1A,12-01-2021 00:00,127.45,255.37,37.38,56.37,46.13,1.06,23.67,15.89,56.33,1,261.94,106.12
12,1A,13-01-2021 00:00,190.3,348.13,36.57,48.35,37.95,1.68,17.73,14.46,71.99,0.68,221.65,79.67
13,1A,14-01-2021 00:00,208.38,354.49,22.68,51.82,29,1.6,26.49,16.82,60.36,0.47,143.83,100.97
14,1A,15-01-2021 00:00,212.24,357.7,32.36,57.61,23.77,1.9,26.36,17.59,70.75,0.53,165.63,86.54
15,1A,16-01-2021 00:00,185.52,339.59,66.71,83.56,23.92,1.91,11.19,13.78,79.9,0.86,263.6,65.83
16,1A,17-01-2021 00:00,153.34,235.59,41.9,45.81,11.54,1.69,18.99,12.2,87.83,0.53,118.59,48.43
17,1A,18-01-2021 00:00,165.98,260.74,55.69,50.43,22.64,1.52,23.02,16.73,79.61,0.47,122.43,59.6
18,1A,19-01-2021 00:00,186.18,341.03,112.13,100.44,24.82,1.65,9.48,14.82,89.64,1.16,267.31,48.9
19,1A,20-01-2021 00:00,89.62,179.14,102.03,106.71,32.49,1.1,22.01,15.72,74.25,1.42,293.66,92.78
20,1A,21-01-2021 00:00,124.41,262.97,53.34,81.19,38.04,1.05,24.18,18.1,53.58,1.25,253.32,102.47
21,1A,22-01-2021 00:00,157.53,277.95,32.91,37.62,27.43,1.3,28.97,16.74,66.48,0.47,125.93,91.7
22,1A,23-01-2021 00:00,106.16,185.73,50.48,45.54,31.33,1.24,21.56,15.48,81.99,0.57,132.37,62.83
23,1A,24-01-2021 00:00,182.02,317.37,57.92,66.4,51.67,1.23,19.9,16.13,74.4,1.62,315.77,57.79
24,1A,25-01-2021 00:00,164.96,293.35,44.03,57.04,53.17,1.1,29.45,15.63,68.29,1.36,298.83,89.84
25,1A,26-01-2021 00:00,133.53,275.56,13.15,39.75,28.45,1.05,33.31,16.07,60.91,0.83,245.77,95.41
26,1A,27-01-2021 00:00,139.15,307.52,59.23,71.44,41.95,1.4,21.86,16.72,49.78,0.87,241.31,94.59
27,1A,28-01-2021 00:00,191.06,393.73,41.64,74.36,54.04,1.27,28.27,16.43,50.78,0.71,237.01,84.12
28,1A,29-01-2021 00:00,148.25,326.44,46.67,70.79,49.04,1.13,33.1,16.49,51.35,1.12,257.34,87.99
29,1A,30-01-2021 00:00,127.43,278.38,48.47,67.46,46.09,1,38.05,17.23,40.96,1.07,267.91,96.33
30,1A,31-01-2021 00:00,124.4,269.73,22.16,38.98,29,1.01,36.06,19.6,31.42,0.61,177.14,110.84
31,1A,01-02-2021 00:00,168.62,343.7,40.5,50.88,40.86,1.33,28.88,20.23,39.76,0.64,182.25,90.63
32,1A,02-02-2021 00:00,184.06,378.03,29.89,42.66,41.31,1.31,34.19,20.78,47.36,0.56,160.3,88.03
33,1A,03-02-2021 00:00,104.97,203.86,9.59,22.47,44.15,1.04,43.68,21.95,50.16,0.51,108.1,85.13
34,1A,04-02-2021 00:00,87.96,181.89,16.21,31.8,36.71,1.04,29.19,20.36,58.34,0.96,112.85,76.15
35,1A,05-02-2021 00:00,119.38,226.9,34.84,44.96,68.66,1.09,21.14,17.46,65.61,1.03,274.6,101
36,1A,06-02-2021 00:00,109.6,221.62,35.75,50.84,64.68,0.9,20.97,18.56,58.15,1.51,299.11,112.03
37,1A,07-02-2021 00:00,102.12,217.86,38.26,56.65,40.21,1.02,25.5,18.68,54.23,1.12,259.65,107.14
38,1A,08-02-2021 00:00,130.88,339.14,30.23,38.79,21.05,1.03,25.95,20.06,57.07,0.7,226.27,104.41
39,1A,09-02-2021 00:00,126.91,250.57,20.7,44.13,50.55,0.97,25.01,21.58,48.93,0.65,192.34,110.11

In [12]:
 df["Date"] = pd.to_datetime(df["Date"])
print(df.dtypes)

Station            object
Date       datetime64[ns]
PM2.5              object
PM10               object
NO                 object
NO2                object
SO2                object
CO                 object
Ozone              object
Temp               object
RH                 object
WS                 object
WD                 object
SR                 object
dtype: object

In [13]:
df.head(40)

,Station,Date,PM2.5,PM10,NO,NO2,SO2,CO,Ozone,Temp,RH,WS,WD,SR
0,1A,2021-01-01,228.53,349.22,19.35,43.16,26.73,1.53,33.3,14.69,49.07,0.42,132.16,69.6
1,1A,2021-02-01,222.37,313.72,13.3,36.83,31.7,1.73,28.9,16.76,46.97,0.47,117.2,43.07
2,1A,2021-03-01,128.14,177.7,15.94,29.33,24.19,1.29,17.46,17.26,70.07,0.5,107.32,26.13
3,1A,2021-04-01,68.44,104.81,26.27,40.26,21.8,1.13,14.43,19.5,72.69,0.72,143.68,70.3
4,1A,2021-05-01,62.51,104.2,22.32,40.63,20.09,0.98,16.6,20.87,73.33,0.67,85.33,70.81
5,1A,2021-06-01,122.99,185.76,56.59,68.72,21.6,1.25,8.85,19.49,88.84,1.15,244.78,24.45
6,1A,2021-07-01,119.15,214.43,38.48,57.54,37.88,1.03,14.09,18.75,75.21,1.23,258.4,89.83
7,1A,2021-08-01,121.51,224.98,33.89,41.65,55.02,1.12,9.3,15.49,86.91,0.88,175.98,41.26
8,1A,2021-09-01,156.75,273.34,40.73,55.38,56.47,1.18,8.75,17.32,81.27,1.56,305.57,51.18
9,1A,2021-10-01,119.35,227.9,37.11,52.61,59.9,0.79,8.27,13.46,80.45,1.76,306,13.24
10,1A,2021-11-01,90.12,218.45,54.14,78.02,39.01,0.97,15.7,13.67,75.12,1.44,293.99,73.27
11,1A,2021-12-01,127.45,255.37,37.38,56.37,46.13,1.06,23.67,15.89,56.33,1,261.94,106.12
12,1A,2021-01-13,190.3,348.13,36.57,48.35,37.95,1.68,17.73,14.46,71.99,0.68,221.65,79.67
13,1A,2021-01-14,208.38,354.49,22.68,51.82,29,1.6,26.49,16.82,60.36,0.47,143.83,100.97
14,1A,2021-01-15,212.24,357.7,32.36,57.61,23.77,1.9,26.36,17.59,70.75,0.53,165.63,86.54
15,1A,2021-01-16,185.52,339.59,66.71,83.56,23.92,1.91,11.19,13.78,79.9,0.86,263.6,65.83
16,1A,2021-01-17,153.34,235.59,41.9,45.81,11.54,1.69,18.99,12.2,87.83,0.53,118.59,48.43
17,1A,2021-01-18,165.98,260.74,55.69,50.43,22.64,1.52,23.02,16.73,79.61,0.47,122.43,59.6
18,1A,2021-01-19,186.18,341.03,112.13,100.44,24.82,1.65,9.48,14.82,89.64,1.16,267.31,48.9
19,1A,2021-01-20,89.62,179.14,102.03,106.71,32.49,1.1,22.01,15.72,74.25,1.42,293.66,92.78
20,1A,2021-01-21,124.41,262.97,53.34,81.19,38.04,1.05,24.18,18.1,53.58,1.25,253.32,102.47
21,1A,2021-01-22,157.53,277.95,32.91,37.62,27.43,1.3,28.97,16.74,66.48,0.47,125.93,91.7
22,1A,2021-01-23,106.16,185.73,50.48,45.54,31.33,1.24,21.56,15.48,81.99,0.57,132.37,62.83
23,1A,2021-01-24,182.02,317.37,57.92,66.4,51.67,1.23,19.9,16.13,74.4,1.62,315.77,57.79
24,1A,2021-01-25,164.96,293.35,44.03,57.04,53.17,1.1,29.45,15.63,68.29,1.36,298.83,89.84
25,1A,2021-01-26,133.53,275.56,13.15,39.75,28.45,1.05,33.31,16.07,60.91,0.83,245.77,95.41
26,1A,2021-01-27,139.15,307.52,59.23,71.44,41.95,1.4,21.86,16.72,49.78,0.87,241.31,94.59
27,1A,2021-01-28,191.06,393.73,41.64,74.36,54.04,1.27,28.27,16.43,50.78,0.71,237.01,84.12
28,1A,2021-01-29,148.25,326.44,46.67,70.79,49.04,1.13,33.1,16.49,51.35,1.12,257.34,87.99
29,1A,2021-01-30,127.43,278.38,48.47,67.46,46.09,1,38.05,17.23,40.96,1.07,267.91,96.33
30,1A,2021-01-31,124.4,269.73,22.16,38.98,29,1.01,36.06,19.6,31.42,0.61,177.14,110.84
31,1A,2021-01-02,168.62,343.7,40.5,50.88,40.86,1.33,28.88,20.23,39.76,0.64,182.25,90.63
32,1A,2021-02-02,184.06,378.03,29.89,42.66,41.31,1.31,34.19,20.78,47.36,0.56,160.3,88.03
33,1A,2021-03-02,104.97,203.86,9.59,22.47,44.15,1.04,43.68,21.95,50.16,0.51,108.1,85.13
34,1A,2021-04-02,87.96,181.89,16.21,31.8,36.71,1.04,29.19,20.36,58.34,0.96,112.85,76.15
35,1A,2021-05-02,119.38,226.9,34.84,44.96,68.66,1.09,21.14,17.46,65.61,1.03,274.6,101
36,1A,2021-06-02,109.6,221.62,35.75,50.84,64.68,0.9,20.97,18.56,58.15,1.51,299.11,112.03
37,1A,2021-07-02,102.12,217.86,38.26,56.65,40.21,1.02,25.5,18.68,54.23,1.12,259.65,107.14
38,1A,2021-08-02,130.88,339.14,30.23,38.79,21.05,1.03,25.95,20.06,57.07,0.7,226.27,104.41
39,1A,2021-09-02,126.91,250.57,20.7,44.13,50.55,0.97,25.01,21.58,48.93,0.65,192.34,110.11

In [14]:
df.sort_values(by='Date', inplace=True)
print(df)

      Station       Date   PM2.5    PM10      NO     NO2    SO2    CO  Ozone  \
0          1A 2021-01-01  228.53  349.22   19.35   43.16  26.73  1.53   33.3
2190       3B 2021-01-01  469.98  515.97  207.95    97.6  24.93  4.58  40.18
30660     26A 2021-01-01  239.94  346.52   38.34   49.52   6.73  3.28  24.38
15330      9B 2021-01-01  330.78  518.81   76.66  133.43    2.5  None   0.85
33215     34A 2021-01-01   118.9  210.59   19.79    7.53  43.47  1.69  32.39
...       ...        ...     ...     ...     ...     ...    ...   ...    ...
9124       3T 2021-12-31  102.75  135.08   48.76   31.04   None  0.31   6.02
30659     25E 2021-12-31  142.83  185.53    78.2   45.85   9.31  2.17  26.74
8759       3S 2021-12-31  239.81  340.31   98.97   56.19   13.3  1.81  11.68
2919       3C 2021-12-31  258.64  362.26   85.15   51.77  10.34   NaN   4.31
33944     35A 2021-12-31  142.18  219.21    9.61   71.85   11.3  0.99  40.94

        Temp     RH    WS      WD      SR
0      14.69  49.07  0.42  132.16    69.6
2190     NaN  80.61  0.44  165.53  118.24
30660   9.18  97.62  3.79    None     185
15330  30.94  85.01  1.48  247.77     NaN
33215  27.18  71.65  1.95  174.65  327.93
...      ...    ...   ...     ...     ...
9124     NaN   None  None    None    None
30659    NaN  87.42   0.2  168.27   12.35
8759     NaN  74.81  0.63   73.95   63.77
2919     NaN  85.04  0.43  141.52   23.21
33944   7.92  61.36  1.18  298.35  267.48

[33945 rows x 14 columns]

In [15]:
df.head(99)

,Station,Date,PM2.5,PM10,NO,NO2,SO2,CO,Ozone,Temp,RH,WS,WD,SR
0,1A,2021-01-01,228.53,349.22,19.35,43.16,26.73,1.53,33.3,14.69,49.07,0.42,132.16,69.6
2190,3B,2021-01-01,469.98,515.97,207.95,97.6,24.93,4.58,40.18,NaN,80.61,0.44,165.53,118.24
30660,26A,2021-01-01,239.94,346.52,38.34,49.52,6.73,3.28,24.38,9.18,97.62,3.79,None,185
15330,9B,2021-01-01,330.78,518.81,76.66,133.43,2.5,None,0.85,30.94,85.01,1.48,247.77,NaN
33215,34A,2021-01-01,118.9,210.59,19.79,7.53,43.47,1.69,32.39,27.18,71.65,1.95,174.65,327.93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12441,5D,2021-01-02,375.48,501.09,11.26,59.8,5.4,2.34,1.11,None,None,None,None,NaN
2951,3D,2021-01-02,133.15,239.26,17.33,22.05,NaN,1.45,15.91,NaN,NaN,NaN,NaN,NaN
12806,6A,2021-01-02,197.72,367.34,1.54,19.08,10.55,None,33.23,30.08,59.7,0.78,59.52,72.54
26676,20D,2021-01-02,99.4,209.08,2.18,1.02,4.12,1.72,5.53,NaN,83.86,0.58,267.76,137.41
1126,2C,2021-01-02,252.53,436.28,33.36,109.34,14.57,2.5,34.25,29.77,66.39,0.84,185.6,49.52

In [16]:
# downloading csv file
cities = pd.DataFrame(df)
cities.to_csv('new222.csv')